### ISSUE TITLE
Asus dashboard

### ISSUE THREAD

**Issue by dels78** [chvvkumar/Monitoring#1]
Hi!!

Thanks a lot for the great wrap up and the awesome dashboards, I just imported most of them and they work great, pending a few little adjustments for multiple hosts and selections, they work pretty much out of the box!

I was wondering if you could please add the Asus dashboard to your project so I can import that one as well?

Thanks!

**Comment by chvvkumar** [comment]
Thank you! I just uploaded the dashboard.

**Comment by chvvkumar** [comment]
I didn't include steps to enable snmp on the router since it varies by model. Let me know if you need steps for this as well and I can post them.

**Comment by kwaczek** [comment]
Hello,

thank you very much for this work.

I am new to it so please help me understand. How should I know which SNMP should I get from Synology? I am talking about telegraf.conf and your sentence "Add them to telegraf.conf using examples others have provided elsewhere in this thread:

Miro

**Comment by chvvkumar** [comment]
> Hello,
> 
> thank you very much for this work.
> 
> I am new to it so please help me understand. How should I know which SNMP should I get from Synology? I am talking about telegraf.conf and your sentence "Add them to telegraf.conf using examples others have provided elsewhere in this thread:
> 
> Miro

@kwaczek 

I will try to go over the config. Please open a new issue to talk about this. This thread is resolved and for a different issue.
