### ISSUE TITLE
Add ability to store monitoring data in VictoriaMetrics

### ISSUE THREAD

**Issue by valyala** [chvvkumar/Monitoring#10]
[VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/) usually requires lower compute resources (CPU, RAM, disk space, disk IO) compared to InfluxDB when processing the same workloads. See [these benchmarks](https://docs.victoriametrics.com/Articles.html#benchmarks) and [these case studies](https://docs.victoriametrics.com/CaseStudies.html). VictoriaMetrics supports data ingestion via Influx line protocol (see [these docs](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf)). It would be great if VictoriaMetrics could be used as monitoring backend instead of InfluxDB.

**Comment by chvvkumar** [comment]
@valyala 

I have zero experience with victoriametrics. It looks interesting and I will check it out. But I can't gurantee support for it at this point. Although, a PR will be most welcome.
