### ISSUE TITLE
Router asus AC88U

### ISSUE THREAD

**Issue by rzae** [chvvkumar/Monitoring#4]
Hi,

First, I would first like to thank you for what your great job.
I have an ASUS RT-AC88U router (merlin) and I have adapted the commands.
This router has 8 ethernet port and I would like to know how to adapt your script to monitor the 8 ports?
Thanks

**Comment by chvvkumar** [comment]
@rzae 

You shouldn't have to do any thing. Ideally since we are parsing `ifTable` field in the SNMP response, as long as iftable has all the port details, the interfaces will automatically be picked up. Here is an example on how we gather interface details from telegraf.conf

```
 ## Interface metrics
   ##
   #  Per-interface traffic, errors, drops
   [[inputs.snmp.table]]
     oid = "IF-MIB::ifTable"
     [[inputs.snmp.table.field]]
       oid = "IF-MIB::ifName"
       is_tag = true
   #  Per-interface high-capacity (HC) counters
   [[inputs.snmp.table]]
     oid = "IF-MIB::ifXTable"
     [[inputs.snmp.table.field]]
       oid = "IF-MIB::ifName"
       is_tag = true
```

**Comment by rzae** [comment]
OK, thanks

I have another question about docker and pihole
In my configuration, I have pihole install in a container synology. I wish monitoring docker and pihole

In the dockerd.json file of my synology:
{
    "registry-mirrors": [],
    "runtimes": {
       "nvidia": {
          "path": "nvidia-container-runtime",
          "runtimeArgs": []
       }
    }
}


There is no risk if I modify the dockerd.json file?

**Comment by chvvkumar** [comment]
Shouldn't be as long as it is valid JSON and the hierarchy is not altered. Add the "hosts" line after the "registry-mirrors" line and don't forget the `,` at the end of the line. Just to be sure, validate the JSON before saving.

Something like this:

```
{
	"registry-mirrors": [],
	"hosts": ["tcp://synology.lan:2375", "unix:///var/run/docker.sock"],
	"runtimes": {
		"nvidia": {
			"path": "nvidia-container-runtime",
			"runtimeArgs": []
		}
	}
}
```
