### ISSUE TITLE
Grafana has moved

### ISSUE THREAD

**Issue by rosegayming** [chvvkumar/Monitoring#6]
https://grafana.challa.co appears to have moved to [https://grafana.com/](https://grafana.com/). The link in the repo desc should be changed.

**Comment by chvvkumar** [comment]
Hello @dudeamax99 

The link for Grafana in the description (I assume you are referring to the one at the top of the description here: https://github.com/chvvkumar/Monitoring#demo) is for my Grafana dashboards I made. Not the official Grafana website.
