### ISSUE TITLE
native method of calling pihole for stats

### ISSUE THREAD

**Issue by zfouts** [chvvkumar/Monitoring#7]
Hello,

While implementing this on my own, I discovered you can actually call the API directly from telegraf, no longer requiring a shell/python script. Please see below:

```
# PiHole monitoring
[[inputs.httpjson]]
  name = "pihole1_stats"
  servers = [
    "http://pihole.example.com/admin/api.php",
  ]
  response_timeout = "5s"
  method = "GET"
```

**Comment by chvvkumar** [comment]
@zfouts 

Interesting! Thank you for pointing that out. I will test that tonight and push the changes after.

**Comment by chvvkumar** [comment]
Added  in 70ce2012655f9676f1f99ba67c6c95105d0774cc

I also updated the dashboard along with the change.

**Comment by zfouts** [comment]
Awesome :) Glad to help @chvvkumar!
